// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var spec;

  spec = require('ddry/modular');

  module.exports = spec({
    title: 'Selenium Safari testing',
    spec: 'spec',
    matchers: 'ddry-selenium-matchers',
    moduleTitles: {
      safari: 'Selenium Safari testing',
      instance: 'Safari driver as it is'
    },
    outside: {
      safari: 'index',
      instance: 'index'
    },
    use: ['safari'],
    initial: {
      instance: []
    }
  });

}).call(this);
