// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var main;

  main = require('./main');

  module.exports = main.apply({
    only: ['safari'],
    methods: {
      safari: {
        only: ['spec_02']
      }
    }
  });

}).call(this);
